version: "3.5"
services:
  crms:
    image: app:v13
    ports:
      - "80:8080"
    networks:
      frontend:
  upload:
    image: app:v:upload_version
    image: app:v:1
    ports:
      - "8082:8080"
    networks:
      frontend:
networks:
  frontend:
    external: true
