version: "3.5"
services:
  crms:
    image: app:v:17
    ports:
      - "8081:8080"
    networks:
      frontend:
  upload:
    image: app:v:upload_version
    ports:
      - "8082:8080"
    networks:
      frontend:
networks:
  frontend:
    external: true
